# Required Status Checks for `main` Branch Protection
#
# This manifest documents the canonical list of required checks.
# If you rename a CI job, you MUST update both this file and the
# branch protection settings (Settings -> Branches -> main).
#
# Added: OMN-2187
# Last verified: 2026-02-14 (PR TBD — gate job added, branch protection applied)

required_checks:
  # -- test.yml (primary CI pipeline) ----------------------------------------
  - name: "CI Tests Gate"
    workflow: test.yml
    job_id: tests-gate
    rationale: >
      Aggregator for the Node version matrix (20.x/22.x/24.x).
      Version additions or removals do not require branch protection updates.

# -- Explicitly excluded -----------------------------------------------------
excluded_checks:
  - name: "Run Tests (20.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.
      Requiring individual entries would break branch protection on version changes.

  - name: "Run Tests (22.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.

  - name: "Run Tests (24.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.

  - name: "Check architecture handshake"
    reason: >
      Path-filtered workflow (only runs when .claude/architecture-handshake.md
      or check-handshake.yml changes). Requiring it would deadlock all other PRs
      because GitHub marks skipped path-filtered checks as "Expected — Waiting
      for status to be reported".
