# Required Status Checks for `main` Branch Protection
#
# This manifest documents the canonical list of required checks.
# If you rename a CI job, you MUST update both this file and the
# branch protection settings (Settings -> Branches -> main).
#
# Added: OMN-2187
# Last verified: 2026-02-21 (OMN-2455 — gate job added, branch protection applied)

required_checks:
  # -- test.yml (primary CI pipeline) ----------------------------------------
  - name: "CI Tests Gate"
    workflow: test.yml
    job_id: tests-gate
    rationale: >
      Aggregator for the Node version matrix (20.x/22.x/24.x).
      Version additions or removals do not require branch protection updates.

# -- Explicitly excluded -----------------------------------------------------
excluded_checks:
  - name: "Run Tests (20.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.
      Requiring individual entries would break branch protection on version changes.

  - name: "Run Tests (22.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.

  - name: "Run Tests (24.x)"
    reason: >
      Individual matrix entry — superseded by the CI Tests Gate aggregator.

  - name: "Check architecture handshake"
    reason: >
      Path-filtered workflow (only runs when .claude/architecture-handshake.md
      or check-handshake.yml changes). Requiring it would deadlock all other PRs
      because GitHub marks skipped path-filtered checks as "Expected — Waiting
      for status to be reported".

  # Cross-reference: this name MUST exactly match the `name:` field of the
  # `schema-compat` job in .github/workflows/onex-schema-compat.yml
  # (currently: `name: ONEX Schema Compatibility Check`).
  # If that job name is renamed, update this entry and branch protection settings.
  - name: "ONEX Schema Compatibility Check"
    reason: >
      Path-filtered workflow (only runs when contracts/** or the workflow itself
      changes). Requiring it would deadlock all other PRs that don't touch
      contract files.
    design_note: >
      Accepted trade-off: PRs that modify contracts/** but are not caught by
      branch protection can still bypass this gate if the check is excluded.
      NOTE: CODEOWNERS enforcement is not yet in place for this repo — no
      .github/CODEOWNERS file exists. The gap is accepted and should be
      tracked in a follow-on ticket to OMN-2455.
