# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
# OMN-6912

name: PR Title Check

on:
  pull_request:
    types: [opened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pr-title:
    uses: OmniNode-ai/onex_change_control/.github/workflows/pr-title-check-reusable.yml@a89a6f30fabf74189195f57b57fcc5d4751f4c48  # onex_change_control main as of 2026-10-02 (OMN-20332)
    permissions:
      pull-requests: read
